export const ADD_BOARD = 'Add board'
export const CHANGE_BOARD_TITLE = 'Change board title'
export const REMOVE_BOARD = 'Remove board'
export const ADD_BOARD_CARD = 'Add board card'
export const CHANGE_BOARD_CARD = 'Change board card'
export const REMOVE_BOARD_CARD = 'Remove board card'
export const ADD_LIST_ITEM = 'Add list item'
export const MOVE_LIST_ITEM = 'Move list item'
